
# SC file
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mystorageaccount
provisioner: disk.csi.azure.com
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuname: Premium_LRS  # Currently shared disk only available with premium SSD
  maxShares: "2"
  cachingMode: None  # ReadOnly cache is not available for premium SSD with maxShares>1
reclaimPolicy: Retain
---
# PVCFile
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: saipvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi  # minimum size of shared disk is 256GB (P15)
  volumeMode: Block
  storageClassName: mystorageaccount
---
#Deployment FIle

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-azuredisk
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-azuredisk
    spec:
      containers:
        - name: deployment-azuredisk
          image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
          volumeDevices:
            - name: azuredisk
              devicePath: /dev/sdx
      volumes:
        - name: azuredisk
          persistentVolumeClaim:
            claimName: saipvc
